name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_KEY: demo
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Ensure dev/test tools even if not in reqs
          pip install pytest bandit detect-secrets

      - name: Run tests
        run: pytest -vv

      - name: Bandit
        run: bandit -qr app

      - name: Detect secrets (non-blocking report)
        run: |
          detect-secrets scan > .secrets.baseline || true
          detect-secrets audit .secrets.baseline --report || true
